apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cvesearch
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: "cvesearch"
        spec:
          containers:
            - name: "cvesearch"
              image: "akoderman/cvesearch:latest"
              env:
              - name: PYTHONDONTWRITEBYTECODE
                value: "1"
              workingDir: /cve-search/sbin  
              command: ["python"]
              args: ["db_updater.py", "-v"]
              volumeMounts:
                - name: "cvesearch-conf"
                  mountPath: "/cve-search/etc"
          restartPolicy: Never
          volumes:
            - name: "cvesearch-conf"
              configMap:
                name: "cvesearch-configmap"

